spring:
  profiles:
    active: dev
  datasource:
    druid:
      #如果连接数据库抛异常则在末尾加上：&allowPublicKeyRetrieval=true
      url: jdbc:mysql://localhost:3306/ishow_order?useSSL=false&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      dbType: com.alibaba.druid.pool.DruidDataSource