spring:
  rabbitmq:
    #host: 192.168.0.76
    host: 119.23.44.103
    port: 5672
    username: admin
    password: admin
  cloud:
    bus:
      refresh:
        enabled: true
      trace:
        enabled: true
      enabled: true