server:
  port: 8555
  servlet:
    context-path: /ishow-user-provider
spring:
  profiles:
    active: dev
  application:
    name: ishow-user-provider
  rabbitmq:
    #host: 192.168.0.76
    host: 119.23.44.103
    port: 5672
    username: admin
    password: admin
  cloud:
    bus:
      refresh:
        enabled: true
      trace:
        enabled: true
      enabled: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
mytest:
  test: some_test_11
info:
  app:
    name: ishow-user-provider