server:
  port: 8555
  servlet:
    context-path: /ishow-user-provider
spring:
  profiles:
    active: dev
  application:
    name: ishow-user-provider
#management:
  #server:
    #servlet:
      #context-path: /ishow-user-provider
mytest:
  test: some_test_1
info:
  app:
    name: ishow-user-provider